name: movenet-dance-demo

channels:
    - apple
    - nvidia
    - conda-forge
    - defaults

dependencies:
    - python=3.8
    - tensorflow-deps=2.7.0
    - h5py=3.1.0
    - ipykernel
    - ffmpeg
    - pip
    - pip:
        - numpy==1.21.2
        - opencv-python==4.5.4.60
        - tensorflow-macos==2.7.0
        - tensorflow-metal==0.3.0
        - tensorflow-hub==0.12.0
        - jupyterlab
        - seaborn
        - pyyaml